apiVersion: v1
kind: ConfigMap
metadata:
  name: zeus-conf
  namespace: gin
data:
  zeus.conf: |-
    server:
      host: "0.0.0.0"
      port: 80
      cert_file: ""
      key_file: ""
    log:
      log_file: "/data/zeus/log/zeus.log"
      log_level: "debug"
      log_format: "text"
      enable_force_colors: true
    database:
      user: ""
      password: ""
      addr: ""
      db_name: ""
      log_level: ""


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: zeus
  name: zeus
  namespace: gin
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: zeus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: zeus
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/huweihuang/zeus:latest
          command:
            - /zeus
            - -c
            - /usr/local/zeus/conf/zeus.conf
          imagePullPolicy: Always
          name: zeus
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - mountPath: /usr/local/zeus/conf
              name: zeus-conf
            - mountPath: /opt/etcd/certs/client/
              name: etcd-client-certs
            - mountPath: /data/zeus
              name: data
      restartPolicy: Always
      volumes:
        - name: zeus-conf
          configMap:
            defaultMode: 511
            name: zeus-conf
        - name: etcd-client-certs
          secret:
            defaultMode: 256
            secretName: etcd-gin-client-certs
        - name: data
          hostPath:
            path: /data/zeus
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: zeus-svc
  namespace: gin
spec:
  ports:
    - name: zeus-port
      nodePort: 32000
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    k8s-app: zeus
  type: NodePort
