server:
  host: "0.0.0.0"
  port: 80
  certFile: ""
  keyFile: ""
log:
  logFile: "log/info.log"
  errorFile: "log/error.log"
  logLevel: "debug"
  logFormat: "json"
  enableColor: false
database:
  user: ""
  password: ""
  addr: ""
  dbName: ""
  logLevel: ""
